-- 1. 親テーブル（他のテーブルから参照されるもの）を先に作成

-- カテゴリ管理
CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);



-- 商品マスター
CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category_id INTEGER REFERENCES categories(id),
    price INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 役職管理（ログイン用）
CREATE TABLE IF NOT EXISTS role (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

-- ユーザー管理（ログイン用）
CREATE TABLE IF NOT EXISTS user_info (
    user_id VARCHAR(50) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL
);

-- 受注履歴
CREATE TABLE IF NOT EXISTS order_histories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    change_quantity INTEGER NOT NULL,
    history_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_histories_product_id_fkey FOREIGN KEY (product_id) 
        REFERENCES products (id)
);

-- 在庫管理
CREATE TABLE IF NOT EXISTS stocks (
    product_id INTEGER PRIMARY KEY REFERENCES products(id),
    quantity INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 入出庫履歴
CREATE TABLE IF NOT EXISTS histories (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    change_quantity INTEGER NOT NULL,
    history_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 受注情報
CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status INTEGER DEFAULT 0,
    customer_name VARCHAR(100),
    zip_code VARCHAR(10),
    address VARCHAR(255)
);

-- 発注情報
CREATE TABLE IF NOT EXISTS purchases (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);